#!/bin/bash
[% c("var/set_default_env") -%]
distdir=/var/tmp/dist/[% project %]
[% IF c("var/linux") %]
  [% pc('gcc', 'var/setup', { compiler_tarfile => c('input_files_by_name/gcc'),
                              hardened_gcc => 0 }) %]
[% END -%]
mkdir /var/tmp/build
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz
cd /var/tmp/build/[% project %]-[% c('version') %]

[% IF c("var/windows") %]
  # CMake 3.16.0 does not respect the prefix when looking for windres
  # This was patched in https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4520
  patch -p1 < $rootdir/windres-selection.patch

  # CMake 3.16.0 does not specify -lcrypt32 when building on win32 with static
  # OpenSSL. This was patched in https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6197
  patch -p1 < $rootdir/findopenssl.patch
[% END -%]

./bootstrap --prefix=$distdir -- -DCMAKE_USE_OPENSSL=OFF
make -j[% c("buildconf/num_procs") %]
make install
cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
