#!/bin/bash
set -x

[% c("var/set_default_env") -%]
distdir=/var/tmp/dist/[% project %]
mkdir -p /var/tmp/build
mkdir -p $distdir

# get our dependencies
mkdir -p /var/tmp/dist/tor
tar -C /var/tmp/dist/tor -xf [% c('input_files_by_name/tor') %]/tor.tar.gz
tar -C /var/tmp/dist -xf [% c('input_files_by_name/tego') %]

mkdir -p /var/tmp/dist/pluggables
tar -C /var/tmp/dist/pluggables -xf $rootdir/pluggable-transports-[% c("var/osname") %].tar.gz

version=[% c("var/tego_version") %]
arch=[% c("arch") %]

cd /var/tmp/build
# windows
[% IF c("var/windows") %]
    mkdir Ricochet\ Refresh
    cp /var/tmp/dist/tego/ricochet-refresh.exe Ricochet\ Refresh/.
    cp /var/tmp/dist/tego/LICENSE Ricochet\ Refresh/.
    cp /var/tmp/dist/tor/Tor/tor.exe Ricochet\ Refresh/.
    # package the version number and license in the zip
    echo $version > Ricochet\ Refresh/VERSION

    # package the pluggables in the zip
    mkdir -p Ricochet\ Refresh/pluggable_transports
    cp /var/tmp/dist/pluggables/obfs4proxy.exe Ricochet\ Refresh/pluggable_transports/.
    cp /var/tmp/dist/pluggables/snowflake-client.exe Ricochet\ Refresh/pluggable_transports/.

    zip -r ricochet.zip Ricochet\ Refresh

    cp ricochet.zip $distdir/ricochet-refresh-$version-windows-$arch.zip
[% END %]

[% IF c("var/linux") %]
    mkdir ricochet-refresh
    cp /var/tmp/dist/tego/ricochet-refresh ricochet-refresh/.
    cp /var/tmp/dist/tego/LICENSE ricochet-refresh/.
    cp /var/tmp/dist/tor/Tor/tor ricochet-refresh/.

    mkdir -p ricochet-refresh/pluggable_transports
    cp /var/tmp/dist/pluggables/obfs4proxy ricochet-refresh/pluggable_transports/.
    cp /var/tmp/dist/pluggables/snowflake-client ricochet-refresh/pluggable_transports/.

    tar -cvf ricochet-refresh-$version-linux-$arch.tar ricochet-refresh
    gzip -9 ricochet-refresh-$version-linux-$arch.tar
    cp ricochet-refresh-$version-linux-$arch.tar.gz  $distdir/.
[% END %]

[% IF c("var/osx") %]
    tar -C /var/tmp/dist -xf $rootdir/[% c('input_files_by_name/libdmg') %]
    export PATH="/var/tmp/dist/libdmg-hfsplus:$PATH"

    cp -a /var/tmp/dist/tego/ricochet-refresh.app ./Ricochet\ Refresh.app
    cp /var/tmp/dist/tor/Contents/MacOS/Tor/tor ./Ricochet\ Refresh.app/Contents/MacOS/.

    mkdir -p ./Ricochet\ Refresh.app/Contents/MacOS/pluggable_transports
    cp /var/tmp/dist/pluggables/obfs4proxy ./Ricochet\ Refresh.app/Contents/MacOS/pluggable_transports/.
    cp /var/tmp/dist/pluggables/snowflake-client ./Ricochet\ Refresh.app/Contents/MacOS/pluggable_transports/.

    # set the background + icon locations
    cp -r $rootdir/resources/darwin/macos_dmg/. .

    genisoimage -V Ricochet\ Refresh -D -R -apple -no-pad -o ricochet-refresh-uncompressed.dmg .
    dmg dmg ricochet-refresh-uncompressed.dmg ricochet-refresh-$version-macos-$arch.dmg

    cp ricochet-refresh-$version-macos-$arch.dmg $distdir/.
[% END %]


# make our output directory and copy outputs
mkdir -p [% dest_dir _ '/' _ c('filename') %]
cp -a $distdir/* [% dest_dir _ '/' _ c('filename') %]/.
