#!/bin/bash
[% c("var/set_default_env") -%]

# setup build tools
[% pc('rust', 'var/setup', { rust_tarfile => c('input_files_by_name/rust') }) %]

[% pc(c('var/build-toolchain'), 'var/setup', { build_toolchain_tarfile => c('input_files_by_name/build-toolchain') }) %]

tar -C $distdir -xf [% c('input_files_by_name/cmake') %]
export PATH=$distdir/cmake/bin:$PATH

# extract dependencies
tar -C $distdir -xf [% c('input_files_by_name/qt') %]
export PATH=$distdir/qt/bin:$PATH
tar -C $distdir -xf [% c('input_files_by_name/tor') %]

# extract source
tar -C $builddir -xf [% project %]-[% c('version') %].tar.gz
tar -C $builddir/[% project %]-[% c('version') %]/src -xf [% c('input_files_by_name/ricochet-refresh-cargo-vendor') %]

cd $builddir/[% project %]-[% c('version') %]/

# setup cargo vendoring
pushd src/libtego_rs
mkdir -p .cargo
cat <<EOF > .cargo/config.toml
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "../vendor/libtego_rs"

[net]
offline=true
EOF
popd

pushd src/ricochet-refresh-qt
mkdir -p .cargo
cat <<EOF > .cargo/config.toml
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "../vendor/ricochet-refresh-qt"

[net]
offline=true
EOF
popd

# generate src tar
pushd $builddir
[% c('tar', {
        tar_src => project _ '-' _ c('version'),
        tar_args => '-czf ' _ dest_dir _ '/src-' _ c('filename'),
    }) %]
popd

# clang needs to be reminded where its c++ includes are
[% IF c("var/macos") -%]
  cppincludes=$distdir/toolchain-macos-clang/clang/include/c++/v1
  export CPLUS_INCLUDE_PATH=$cppincludes:$CPLUS_INCLUDE_PATH
  export PKG_CONFIG_LIBDIR=$sysrootdir/lib/pkgconfig
[% END -%]

[% IF c("var/linux-cross") -%]
  export PKG_CONFIG_LIBDIR="/usr/lib/[% c("var/compiler_target") %]/pkgconfig:/usr/share/pkgconfig"
[% END -%]

CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=MinSizeRel
                -DFORCE_QT5=ON
                -DUSE_SUBMODULE_FMT=ON
                -DSTATIC_QT_ROOT_DIR=$distdir/qt
                -DSTATIC_QT=ON
                -DTEGO_STATIC_BUILD=ON"

# # Always enable logging
[% IF c("var/testbuild") %]
    CMAKE_FLAGS="-DENABLE_RICOCHET_REFRESH_LOGGING=ON $CMAKE_FLAGS"
[% END -%]

[% IF c("var/pluggable_transports") %]
    CMAKE_FLAGS="-DENABLE_PLUGGABLE_TRANSPORTS=ON $CMAKE_FLAGS"
    CMAKE_FLAGS="-DTOR_EXPERT_BUNDLE=$rootdir/[% c('input_files_by_name/tor-expert-bundle') %] $CMAKE_FLAGS"
[% END -%]

# Set toolchain file
[% IF c("var/linux-i686") -%]
    CMAKE_FLAGS="-DCMAKE_TOOLCHAIN_FILE=../src/cmake/toolchains/i386-linux-gnu.cmake $CMAKE_FLAGS"
[% END -%]
[% IF c("var/linux-cross") -%]
    CMAKE_FLAGS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=[% c("var/arch") %] $CMAKE_FLAGS"
[% END -%]
[% IF c("var/windows") -%]
    CMAKE_FLAGS="-DCMAKE_SYSTEM_NAME=Windows $CMAKE_FLAGS"
    [% IF c("var/windows-i686") -%]
        CMAKE_FLAGS="-DCMAKE_SYSTEM_PROCESSOR=i386 $CMAKE_FLAGS"
    [% END -%]
    [% IF c("var/windows-x86_64") -%]
        CMAKE_FLAGS="-DCMAKE_SYSTEM_PROCESSOR=x86_64 $CMAKE_FLAGS"
    [% END -%]
    CMAKE_FLAGS="-DCMAKE_C_COMPILER_AR=$distdir/toolchain-windows-clang/bin/[% c('var/compiler_target') -%]-ar $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_CXX_COMPILER_AR=$distdir/toolchain-windows-clang/bin/[% c('var/compiler_target') -%]-ar $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_C_COMPILER_RANLIB=$distdir/toolchain-windows-clang/bin/[% c('var/compiler_target') -%]-ranlib $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_CXX_COMPILER_RANLIB=$distdir/toolchain-windows-clang/bin/[% c('var/compiler_target') -%]-ranlib $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_C_COMPILER_TARGET=[% c('var/compiler_target') %] $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_CXX_COMPILER_TARGET=[% c('var/compiler_target') %] $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_ASM_COMPILER_TARGET=[% c('var/compiler_target') %] $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_PREFIX_PATH=$distdir/toolchain-windows-clang/[% c('var/compiler_target') -%]/lib/ $CMAKE_FLAGS"
[% END -%]
[% IF c("var/macos") -%]
    # Set AR and RANLIB on macos
    CMAKE_FLAGS="-DCMAKE_AR=$OSX_AR -DCMAKE_RANLIB=$OSX_RANLIB $CMAKE_FLAGS"

    # CMake doesn't honour the CMAKE_AR and CMAKE_RANLIB vars when checking for
    # IPO, see https://github.com/emscripten-core/emscripten/issues/11143.
    # Workaround this by CMAKE_(C|CXX)_COMPILER_(AR|RANLIB)
    CMAKE_FLAGS="-DCMAKE_C_COMPILER_AR=$OSX_AR -DCMAKE_CXX_COMPILER_AR=$OSX_AR $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_C_COMPILER_RANLIB=$OSX_RANLIB -DCMAKE_CXX_COMPILER_RANLIB=$OSX_RANLIB $CMAKE_FLAGS"

    # Setting CXX in toolchain-macos-clang breaks protoc's build, as it ends up
    # creating an unusable binary. Instead, toolchain-macos-clang set's it in
    # OSX_CXX, so as to not conflict with protoc
    export CXX="$OSX_CXX"

    CMAKE_FLAGS="-DCMAKE_SYSTEM_NAME=Darwin $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_SYSTEM_PROCESSOR=[% c('var/arch') %] $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_C_COMPILER_TARGET=[% c('var/arch') %] $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_CXX_COMPILER_TARGET=[% c('var/compiler_target') %] $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_ASM_COMPILER_TARGET=[% c('var/compiler_target') %] $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_PREFIX_PATH=$distdir/toolchain-macos-clang/clang/lib/ $CMAKE_FLAGS"
    CMAKE_FLAGS="-DCMAKE_FRAMEWORK_PATH=$distdir/toolchain-macos-clang/MacOSX[% pc("toolchain-macos-clang", "version") %].sdk/System/Library/Frameworks $CMAKE_FLAGS"
[% END -%]
CMAKE_FLAGS="-DCMAKE_INSTALL_PREFIX=$distdir/ricochet-refresh-dist $CMAKE_FLAGS"

mkdir build && cd build
export SOURCE_DATE_EPOCH='[% c("timestamp") %]'
RICOCHET_REFRESH_VERSION=[% c('version') %] cmake -S ../src $CMAKE_FLAGS '-DCARGO_FLAGS=[% pc('rust', 'var/cargo-flags') %]'

cmake --build . -j[% c('num_procs') %]
cmake --install .

bindir=$projdir

mv $distdir/ricochet-refresh-dist/bin/* $projdir

[% IF c("var/pluggable_transports") -%]
# remove extraneous non-executable files
find $bindir/pluggable_transports -type f ! -executable -exec rm {} \;
[% END -%]

# tor
cp $distdir/tor/bin/tor[% IF c("var/windows") %].exe[% END %] $bindir/.

# license files
cp $builddir/[% project %]-[% c('version') %]/LICENSE $distdir/ricochet-refresh/.

cd $distdir
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
