#!/bin/bash
[% c("var/set_default_env") -%]

tar xf [% project %]-[% c("version") %].tar.gz
mv [% project %]-[% c("version") %] llvm-project-source
[% c('tar', {
        tar_src => [ 'llvm-project-source' ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
