#!/bin/bash
[% c("var/set_default_env") %]

# setup rust
[% pc('rust', 'var/setup', { rust_tarfile => c('input_files_by_name/rust') }) %]

tar -C $builddir -xf [% project %]-[% c('version') %].tar.[% c('compress_tar') %]

mkdir -p $builddir/vendor
cd $builddir

pushd [% project %]-[% c('version') %]/src/libtego_rs
  cargo vendor --locked --manifest-path Cargo.toml $builddir/vendor/libtego_rs
popd

pushd [% project %]-[% c('version') %]/src/ricochet-refresh
  cargo vendor --locked --manifest-path Cargo.toml $builddir/vendor/ricochet-refresh
popd

[% c('tar', {
  tar_src => [ 'vendor' ],
  tar_args => '-caf ' _ dest_dir _ '/' _ c('filename'),
  }) %]
