#!/bin/bash
[% c("var/set_default_env") -%]

shopt -s globstar

unzip dnspython-[% c('version') %].zip

mkdir -p /var/tmp/dist/[% project %]

cd $rootdir/dnspython*/[% project %]
cp --parents **/*.py /var/tmp/dist/[% project %]/

cd /var/tmp/dist/
[% c('tar', {
        tar_src => '.',
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
