#!/bin/bash
[% c("var/set_default_env") -%]

builddir=$builddir

tar -C $distdir -xf [% c('input_files_by_name/cmake') %]
tar -C $projdir -xf [% c('input_files_by_name/clang') %]
tar -C $projdir -xf [% c('input_files_by_name/cctools') %]
tar -C $builddir -xf [% c('input_files_by_name/llvm-project-source') %]

# copy over xcode mocks
mkdir $projdir/xcode_tools
cp $rootdir/xcrun $projdir/xcode_tools/xcrun
cp $rootdir/xcode-select $projdir/xcode_tools/xcode-select

patch -p1 < $rootdir/tools.diff

sysrootdir=$projdir/MacOSX[% c("version") %].sdk/
mkdir -p $sysrootdir
cd $sysrootdir
python3 "$rootdir/unpack-sdk.py" "$rootdir/[% c('input_files_by_name/SDK') %]" "Library/Developer/CommandLineTools/SDKs/MacOSX[% c('version') %].sdk"

arch=[% c("var/macos_arch") %]
clangdir=$projdir/clang/bin
cctoolsdir=$projdir/cctools/bin
target=[% c("var/compiler_target") %]
# We still need to put the cctoolsdir on the path. That's because of `lipo`. See
# the respective comment in the cctools build script.
export PATH="$distdir/cmake/bin:$cctoolsdir:$PATH"

# See tor-browser.git/taskcluster/scripts/misc/build-llvm-common.sh
export MACOSX_DEPLOYMENT_TARGET=[% c("var/macosx_deployment_target") %]
target=[% c("var/compiler_target") %]
arch=[% c("var/arch_macos") %]
[% IF c("var/macos-aarch64") -%]
  clangwrappersdir=$projdir/clang/wrappers
  mkdir $clangwrappersdir
  compiler_wrapper() {
    echo exec $clangdir/$1 -mcpu=apple-m1 \"\$@\" > $clangwrappersdir/$1
    chmod +x $clangwrappersdir/$1
  }
  compiler_wrapper clang
  compiler_wrapper clang++
  clang=$clangwrappersdir/clang
[% ELSE -%]
  clang=$clangdir/clang
[% END -%]

COMMON_CMAKE_FLAGS="
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_INSTALL_PREFIX=$projdir/clang/lib/clang/[% pc("clang", "version") %]
  -DCMAKE_C_COMPILER=$clang
  -DCMAKE_CXX_COMPILER=$clang++
  -DCMAKE_AR=$clangdir/llvm-ar
  -DCMAKE_RANLIB=$clangdir/llvm-ranlib
  -DCMAKE_LINKER=$clangdir/ld64.lld
  -DCMAKE_LIPO=$clangdir/llvm-lipo
  -DCMAKE_C_COMPILER_TARGET=$target
  -DCMAKE_CXX_COMPILER_TARGET=$target
  -DCMAKE_ASM_COMPILER_TARGET=$target
  -DCMAKE_SYSTEM_NAME=Darwin
  -DCMAKE_SYSTEM_VERSION=$MACOSX_DEPLOYMENT_TARGET
  -DCMAKE_OSX_SYSROOT=$sysrootdir
  -DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld
  -DCMAKE_SHARED_LINKER_FLAGS=-fuse-ld=lld
  -DDARWIN_osx_ARCHS=$arch
  -DDARWIN_osx_SYSROOT=$sysrootdir
  -DDARWIN_macosx_OVERRIDE_SDK_VERSION=11.0
  -DDARWIN_osx_BUILTIN_ARCHS=$arch
  -DLLVM_DEFAULT_TARGET_TRIPLE=$target
  -DLLVM_ENABLE_ASSERTIONS=OFF
  -DLLVM_CONFIG_PATH=$clangdir/llvm-config
  "

mkdir $builddir/faketools

# compiler-rt build script expects to find `codesign` in $PATH.
# Give it a fake one.
echo "#!/bin/sh" > $builddir/faketools/codesign
chmod +x $builddir/faketools/codesign

# cmake makes decisions based on the output of the mac-only sw_vers, which is
# obviously missing when cross-compiling, so create a fake one. The exact
# version doesn't really matter: as of writing, cmake checks at most for 10.5.
echo "#!/bin/sh" > $builddir/faketools/sw_vers
echo echo 10.12 >> $builddir/faketools/sw_vers
chmod +x $builddir/faketools/sw_vers

export PATH=$PATH:"$builddir/faketools"
# End of Moz's tricks

mkdir build_compiler_rt
cd build_compiler_rt

# And we build compiler-rt by following taskcluster/scripts/misc/build-compiler-rt.sh.
cmake $builddir/llvm-project-source/compiler-rt -G "Unix Makefiles" \
  $COMMON_CMAKE_FLAGS

make -j[% c("num_procs") %]
make install

cd $builddir/llvm-project-source

cmake -G "Unix Makefiles" -S runtimes -B build\
      -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \
      $COMMON_CMAKE_FLAGS

cd build
make -j[% c("num_procs") %]
make install

cd $projdir/cctools/bin
ln -s ../../clang/bin/clang $target-clang
ln -s ../../clang/bin/clang++ $target-clang++

# setup some paths expected by Xcode tools
mkdir -p $projdir/Developer/SDKs
cd $projdir/Developer/SDKs
ln -s ../../MacOSX[% c("version") %].sdk MacOSX[% c("version") %].sdk

mkdir -p $projdir/Developer/Toolchains/XcodeDefault.xctoolchain
cd $projdir/Developer/Toolchains/XcodeDefault.xctoolchain
ln -s ../../../clang usr

cd $distdir
[% c('tar', {
   tar_src => [ project ],
   tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
}) %]
