#!/bin/sh
set -x
[% c("var/set_default_env") -%]
# reset HOME which was changed by var/set_default_env, for gpg
[% IF ENV.HOME %]export HOME="[% ENV.HOME %]"[% END %]
destdir="[% dest_dir _ '/' _ c("var/publish_dir") %]"
mkdir -p "$destdir"
[% IF c("var/tego-windows-i686") -%]
  mv [% c('input_files_by_name/windows-i686') %]/* "$destdir"/
[% END -%]
[% IF c("var/tego-windows-x86_64") -%]
  mv [% c('input_files_by_name/windows-x86_64') %]/* "$destdir"/
[% END -%]
[% IF c("var/tego-osx-x86_64") -%]
  mv [% c('input_files_by_name/osx-x86_64') %]/* "$destdir"/
[% END -%]
[% IF c("var/tego-linux-i686") -%]
  mv [% c('input_files_by_name/linux-i686') %]/* "$destdir"/
[% END -%]
[% IF c("var/tego-linux-x86_64") -%]
  mv [% c('input_files_by_name/linux-x86_64') %]/* "$destdir"/
[% END -%]
cd "$destdir"
# sha256 the output files from tego-package
sha256sum $(ls -1 tego-package-* *.exe *.tar.xz *.dmg *.mar *.zip *.tar.gz *.apk *.json | sort) > sha256sums-build.txt
cat sha256sums-build.txt
