#!/bin/bash
[% c("var/set_default_env") -%]

tar -C $builddir -xf [% project %]-[% c('version') %].tar.xz
cd $builddir/[% project %]-[% c('version') %]

[% IF c("var/linux-cross") -%]
  projdir=$projdir-cross-[% c("var/arch") %]
  mkdir -p $projdir
[% END -%]

./configure --prefix=$projdir --disable-shared --enable-static \
        --target=[% c("var/compiler_target") %] --disable-multilib \
        --enable-lto --disable-gdb --enable-deterministic-archives

make -j[% c("num_procs") %]
make install

cd $distdir
[% c('tar', {
        tar_src => [ c('var/distdir') ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
