#!/bin/bash
[% c("var/set_default_env") -%]

[% pc(c('var/build-toolchain'), 'var/setup', { build_toolchain_tarfile => c('input_files_by_name/build-toolchain') }) %]

tar -C $builddir -xf [% project %]-[% c('version') %].tar.gz
cd $builddir/[% project %]-[% c('version') %]

./autogen.sh
./configure --disable-shared --disable-libevent-regress --disable-samples --disable-openssl --prefix=$projdir --host=[% c('var/compiler_target') %]

make -j[% c('num_procs') %]
make install

cd $distdir
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
