#!/bin/bash
set -x

destdir=/var/tmp/dist/[% project %]
mkdir -p $destdir
touch $destdir/ricochet

cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
